### ISSUE TITLE
Field->SET does not work

### ISSUE THREAD

**Issue by 211666** [DataTables/Editor-PHP#21]
PHP 8.1
MYSQL 8.0.30

Recently we booted up a fairly big project this includes Datatables Editor PHP being one of them.

It worked pretty great so far, but we stumbled upon one fairly big problem. This concludes where we use the set method after instantiating a field and providing it's validators. We set it to usually Field::SET_CREATE, but in some use cases this does not work and only works in certain conditions let me provide u with an example.

For example: I define a field LEFT JOIN method from editor, the left join works but for some reason if I set the field of that joined field on Field::SET_CREATE datatables editor does not seem to comply when I create a new row. Instead completed the row as expected but leaves that value to a null or default value provided by the database (MYSQL).

My question was have there been any problems reported relevant to this if not? Could u maybe highlight if u ever fixed a problem like this we're gonna update datatables editor package via composer as of right now after this post is made. I just would like to know.

**Comment by AllanJard** [comment]
The libraries don't operate an insert on a joined table when creating a new row. The way such a case is handled in Editor is [like this](https://editor.datatables.net/examples/datatables/nested.html) which nested child editing.
