### ISSUE TITLE
Composer 2.0: non psr-4 class DataTables\Vendor\htmLawed

### ISSUE THREAD

**Issue by FGIKCM** [DataTables/Editor-PHP#3]
With latest versions of Composer, a warning appears when getting the library:

> Deprecation Notice: Class DataTables\Vendor\htmLawed located in *hidden*/vendor/datatables.net/editor-php\Vendor\htmLawed\htmLawed.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://*hidden*/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201

As `htmLawed.php` is in `Vendor/htmLawed` folder, it should be in a namespace `DataTables\Vendor\htmLawed`, I think. Or be in the parent folder?

Best regards

**Comment by DataTables** [comment]
Thank you - we'll get this sorted for the next release!

**Comment by DataTables** [comment]
I've just been looking into this, and I'm not seeing that notice pop up:

```
$ php ../composer.phar -vv install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Dependency resolution completed in 0.000 seconds
Analyzed 49 packages to resolve dependencies
Analyzed 71 rules to resolve dependencies
Package operations: 1 install, 0 updates, 0 removals
Installs: datatables.net/editor-php:1.9.4
  - Installing datatables.net/editor-php (1.9.4): Loading from cache
 Extracting archive    REASON: Required by the root package: Install command rule (install datatables.net/editor-php 1.8.0|install datatables.net/editor-php 1.8.1|install datatables.net/editor-php 1.9.0|install datatables.net/editor-php 1.9.1|install datatables.net/editor-php 1.9.2|install datatables.net/editor-php 1.9.3|install datatables.net/editor-php 1.9.4)

Writing lock file
Generating autoload files
```

```
$ php ../composer.phar --version
Composer version 1.10.13 2020-09-09 11:46:34
```

Is there something I need to do to get that error to show?

**Comment by FGIKCM** [comment]
I just tried to update to the same Composer version as yours, and I can still reproduce this:
```console
D:\xxx>composer -V
Composer version 1.10.13 2020-09-09 11:46:34

D:\xxx>composer dump-autoload
Generating optimized autoload files
Deprecation Notice: Class DataTables\Vendor\htmLawed located in D:/xxx/vendor/datatables.net/editor-php\Vendor\htmLawed\htmLawed.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/xxx/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Generated optimized autoload files containing 2082 classes
```

But in my `composer.json` file, I see that I have `optimize-autoloader` enabled, ([the doc](https://getcomposer.org/doc/articles/autoloader-optimization.md) says it should be the default value for production env.)

```json
{
	...
	"require" : {
		...
	},
	"config" : {
		"optimize-autoloader": true
	}
}
```

So, perhaps this would do the trick?
```console
composer dump-autoload --optimize
```

**Comment by DataTables** [comment]
That'll do it - thanks! I've just [committed a fix](https://github.com/DataTables/Editor-PHP/commit/c1fc3834d55d5cf4dac6f19d6ab7ab3fc095ec44) to address this and will push it out shortly.
