### ISSUE TITLE
Not supporting PHP 8.4.1 :)

### ISSUE THREAD

**Issue by EmadAlmahdi** [DataTables/Editor-PHP#41]

**Comment by AllanJard** [comment]
[Fixed here](https://github.com/DataTables/Editor-PHP/commit/acb2b497425a7ab222d48b445d2275ff461fbcbe). Thanks for letting me know of that error.

**Comment by EmadAlmahdi** [comment]
Welcome!

It seems the issue description didn't make it through when I posted earlier – sorry about that!

To address the matter, there are additional changes needed to ensure full support for PHP 8.4.1. For instance, the composer.json file requires updates to work with the new version

**Comment by AllanJard** [comment]
Thanks - I missed that. Corrected now.

Was there anything else that was giving you a problem with PHP 8.4?
